// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} filePath
 * @param {string} driveName
 * @param {boolean} eject
 * @returns {$CancellablePromise<void>}
 */
export function FlashDrive(filePath, driveName, eject) {
    return $Call.ByID(1015167144, filePath, driveName, eject);
}

/**
 * @returns {$CancellablePromise<$models.Drive[]>}
 */
export function ListDrives() {
    return $Call.ByID(3376589995).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string | null} filepath
 * @returns {$CancellablePromise<$models.SourceFile | null>}
 */
export function SelectFile(filepath) {
    return $Call.ByID(1833969076, filepath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Drive.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.SourceFile.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
