// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Drive {
    /**
     * Creates a new Drive instance.
     * @param {Partial<Drive>} [$$source = {}] - The source object to create the Drive.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("capacity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["capacity"] = 0;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("removable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["removable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Drive instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Drive}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Drive(/** @type {Partial<Drive>} */($$parsedSource));
    }
}

export class SourceFile {
    /**
     * Creates a new SourceFile instance.
     * @param {Partial<SourceFile>} [$$source = {}] - The source object to create the SourceFile.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("basename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["basename"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("validGPT" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["validGPT"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceFile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceFile(/** @type {Partial<SourceFile>} */($$parsedSource));
    }
}
