// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FlashDrive(arg1, arg2) {
  return window['go']['main']['App']['FlashDrive'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListDrives() {
  return window['go']['main']['App']['ListDrives']();
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}
