// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FlashDrive(arg1:string,arg2:string):Promise<void>;

export function ListDrives():Promise<Array<main.Drive>>;

export function SelectFile(arg1:any):Promise<main.SourceFile>;
