// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {block} from '../models';
import {main} from '../models';

export function FlashDrive(arg1:string,arg2:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ListDrives():Promise<Array<block.Disk>>;

export function SelectFile(arg1:any):Promise<main.SourceFile>;
